#select * from bank_user;
#SELECT `db_project`.`login_user`('mon', '1234') AS `login_result`;
#CALL `db_project`.`change_password`(1111111111, '1234', '1234');
# CALL `db_project`.`get_accounts`(1111111111);
# select * from transaction;
#CALL `db_project`.`last_n_transactions`(1, 2);
#CALL `db_project`.`transaction_by_date`(1, '2023-01-01', '2023-12-31');
# CALL `db_project`.`acc_info`(1111111111);
# SELECT `db_project`.`acc_name`(1) AS `account_holder_name`;
# CALL `db_project`.`suspend_acc`(2);
# select * from bank_account where suspended=0;
# select * from bank_account;
#CALL `db_project`.`do_transaction`('1111222233334444', '1212121211111112', 1000, @result);
# SELECT @result AS `transaction_result`;
# select * from transaction;
# SELECT `db_project`.`calculate_loan_score`(4) AS `loan_score`;
# CALL `db_project`.`get_loan`(4, @result);
# SELECT @result AS `loan_result`;
# select * from loan;
# select * from loan_payment;
# CALL `db_project`.`get_user_loans`(1);
# CALL `db_project`.`loan_payments`(1);
#CALL `db_project`.`pay_last_payment`(1, @result);
#SELECT @result AS `payment_result`;
